baseURL = "" # Cập nhật sau khi có tên miền
languageCode = "vi-VN"
title = "Blog Backlink 1D"
theme = "PaperMod"
enableRobotsTXT = true
[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1

[params]
  description = "Blog ahr"
  keywords = ["backlink", "SEO", "bl1d", "backlink1d"]
  ShowReadingTime = true
  ShowShareButtons = true

[outputFormats]
  [outputFormats.robotstxt]
    mediaType = "text/plain"
    baseName = "robots"
    isPlainText = true
    notAlternative = true

[outputs]
home = ["HTML", "RSS", "robotstxt"]
